// const sketches = [
//     "Atomic Fishes",
//     "Drawn Lines",
//     "Water Flower",
//     "Pyramids",
//     "Shifting Sands",
//     "Returning Spheres",
//     "Asteroid",
//     "Creative Link",
//     "Slick Link",
//     "Origin Lines",
//     "Landscape",
//     "Flow Fields",
//     "Sunset",
//     "Fluid Grid",
//     "Camo",
//     "Waavy Input",
//     "Rainbow Road",
//     "Depth Lines",
//     "Scales",
//     "Galaxy",
//     "Roe v Wade",
// ];
